### ISSUE TITLE
[Question] How to use this?

### ISSUE THREAD

**Issue by PalaNolho** [zigurous/unity-blend-shaders#2]
Hi, I found your bend assets and wanted to use it on UI elements.

Is it possible? how?

many thanks in advance

**Comment by adamgraham** [comment]
> Hi, I found your bend assets and wanted to use it on UI elements.
> 
> Is it possible? how?
> 
> many thanks in advance

I don't believe these will work on UI elements. Blending between different UI elements would need much more advanced shaders. These shaders are pretty simple and let you blend textures or sprites within a single material. There are also standalone blend functions that can be included and used within your own shaders though.
